### ISSUE TITLE
Use SMBIOS to fetch values when possible?

### ISSUE THREAD

**Issue by WolfWings** [gershnik/wsdd-native#11]
Noticed the 'FIXME' in [wsd_server.cpp](https://github.com/gershnik/wsdd-native/blob/49d40dbe8d904383874254077a1c2774f922150f/src/wsd_server.cpp#L197) and realized I'd done some research when I'd submitted a pull request towards WSDD2 before finding this project, and at least on Linux and FreeBSD you can fetch these values from the SMBIOS entries on x86-based systems, if that's helpful?

Also sorry if I'm not submitting PRs but only Issues, I'm not very comfortable diving into C++ codebases unfortunately.

FreeBSD: (I haven't confirmed if it's on OpenBSD and NetBSD yet, I don't have any installs of those currently.)
```
$ kenv | grep smbios
hint.smbios.0.mem="0xbfbfb000"
smbios.bios.reldate="05/22/2023"
smbios.bios.vendor="VMware, Inc."
smbios.bios.version="VMW201.00V.21805430.B64.2305221830"
smbios.chassis.maker="No Enclosure"
smbios.chassis.serial="None"
smbios.chassis.tag="No Asset Tag"
smbios.chassis.type="Other"
smbios.chassis.version="N/A"
smbios.memory.enabled="16777216"
smbios.planar.maker="Intel Corporation"
smbios.planar.product="440BX Desktop Reference Platform"
smbios.planar.serial="None"
smbios.planar.version="None"
smbios.socket.enabled="16"
smbios.socket.populated="16"
smbios.system.maker="VMware, Inc."
smbios.system.product="VMware20,1"
smbios.system.serial="VMware-56 4d d1 5f af 73 74 27-17 bb 1c ce 60 f8 c4 68"
smbios.system.uuid="5fd14d56-73af-2774-17bb-1cce60f8c468"
smbios.system.version="None"
smbios.version="2.6"
```

Linux:
```
$ grep . $(ls -ld /sys/class/dmi/id/* | grep -E "^[-]r.....r" | grep -Ev "(uevent|modalias)" | awk '{print $9}')
/sys/class/dmi/id/bios_date:02/21/2024
/sys/class/dmi/id/bios_release:5.6
/sys/class/dmi/id/bios_vendor:Intel Corp.
/sys/class/dmi/id/bios_version:BECFL357.86A.0097.2024.0221.1015
/sys/class/dmi/id/board_name:NUC8BEB
/sys/class/dmi/id/board_vendor:Intel Corporation
/sys/class/dmi/id/board_version:J72693-303
/sys/class/dmi/id/chassis_type:3
/sys/class/dmi/id/chassis_vendor:Intel Corporation
/sys/class/dmi/id/chassis_version:2.0
/sys/class/dmi/id/ec_firmware_release:3.26
/sys/class/dmi/id/product_family:Intel NUC
/sys/class/dmi/id/product_name:NUC8i3BEH
/sys/class/dmi/id/product_sku:BOXNUC8i3BEH
/sys/class/dmi/id/product_version:J72753-302
/sys/class/dmi/id/sys_vendor:Intel(R) Client Systems

$ sudo grep . $(ls -ld /sys/class/dmi/id/* | grep -E "^[-]r.....[^r]" | awk '{print $9}')
/sys/class/dmi/id/board_serial:GEBE843005X7
/sys/class/dmi/id/product_serial:G6BE84300Q9L
/sys/class/dmi/id/product_uuid:1f261432-e23e-6911-841c-94c691a6afd8
```

Note that some of the values are only accessible as root on Linux so I broke things up into the 'sudo grep' and 'normal grep' lines to show example values captured from the Intel NUC I had handy, and I filtered out the uevent/modalias entries as they just have very spammy output that I don't thin is relevant in this case.

**Comment by gershnik** [comment]
Thank you, this is awesome! 

There are a few reasons I left that "fixme" in the code and never pursued this further. 

First and foremost is that Windows _doesn't show this info anywhere_! 🙂 In the old days (e.g. Windows 7 and before) you could right click a computer in the Network view and select Properties but this whole thing is gone from Windows 10 and 11 for _computers_. Other WSD discovered devices do have a nice property page that lists the info but not computers.

Second reason is as you noticed the ways to get the info are really platform specific - there is no standard API and in fact no API at all. Which means lots of tedious, hard to test code. I'd do it though, if it brought tangible benefits but see above.

Finally there is now an ability to specify custom metadata. This is done precisely to make it possible to use wsdd-native with non-SMB servers but it could be used with SMB too. For these you can specify precisely what metadata to send via a custom XML file (see the examples  [here](https://github.com/gershnik/wsdd-native/tree/master/config/metadata)). For the few users who need this it provides an easy way to specify whatever they want. 

I _could_ fetch some fields from smbios and make them available as $PLACEHOLDERS I guess if there is enough interest in this but its a lot of work and testing so I'd wait for explicit user request.

**Comment by WolfWings** [comment]
I... had never realized before now Windows removed the Properties tab just for Computers.

WTBoop, I thought alt-enter was just broken since I hadn't right-clicked on anything in forever, since yeah you used to be able to look at those details.

Between that, and yeah the platform-specificality versus how platform-agnostic the codebase is right now, since it's no actual benefit honestly yeah this is moot.

I honestly hadn't realized that Windows did away with such a useful feature, so yeah, that's not a 'fixme' then. XD Guess just replacing that with a comment-note that Windows ignores these values so they're generic placeholders would be more apt instead.

Sincerely thank you for your patience with this flurry of issues I've filed lately. :)

**Comment by gershnik** [comment]
I suspect someone on Windows team looked into nicely presenting different info brought from old-style broadcasts, WSD, whatever else they using and planning to use and said "nah, it's too much work, let's just disable the property page" 😂

One other reason that querying SMBIOS might be problematic is that under systemd wsdd-native never runs as root at all. It is set to use DynamicUser there. 

No problem at all w.r.t. issues. These are all really good ones!

**Comment by WolfWings** [comment]
Yeah running as non-root was why I split out the 'root only' values from the 'world readable' values, which only the 'serial number' values are root-only on Linux.

I guess thanks to whatever Microsoft intern did that change that code isn't really 'fixme' afterall. 🤣
