### ISSUE TITLE
Fails to install on Raspberry Pi (no armhf support?)

### ISSUE THREAD

**Issue by andrewcrook** [gershnik/wsdd-native#2]
I tried to install on a Raspberry PI 3B using instructions
I seem to have an issue with the architecture armhf not being supported

```
WSDDN_MATCHING_DIST=`(source /etc/os-release; \
  mine=${UBUNTU_CODENAME:-${VERSION_CODENAME:-UNKNOWN}}; \
  supported=($(wget -qO- https://www.gershnik.com/apt-repo/conf/supported-dists.txt)); \
  if printf '%s\0' "${supported[@]}" | grep -Fxzq  -- "$mine"; then echo $mine; else echo ${supported[0]}; fi \
)`
```
```
> echo $WSDDN_MATCHING_DIST
bullseye
```
```
echo "deb" \
"[arch=$(dpkg --print-architecture)]" \
"https://www.gershnik.com/apt-repo/" \
"$WSDDN_MATCHING_DIST" \
"main" \
  | sudo tee /etc/apt/sources.list.d/wsddn.list >/dev/null
```
```
> cat  /etc/apt/sources.list.d/wsddn.list
deb [arch=armhf] https://www.gershnik.com/apt-repo/ bullseye main
```

```
> sudo apt update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Get:2 http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian bullseye InRelease [15.0 kB]
Hit:3 https://packages.cisofy.com/community/lynis/deb stable InRelease
Hit:4 https://download.docker.com/linux/raspbian bullseye InRelease
Hit:5 https://mistertea.github.io/debian-et/debian-source buster InRelease
Get:6 https://www.gershnik.com/apt-repo bullseye InRelease [2,848 B]
Fetched 17.8 kB in 3s (6,644 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://www.gershnik.com/apt-repo bullseye InRelease' doesn't support architecture 'armhf’
```

```
uname -a
Linux pihole 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
```

**Comment by gershnik** [comment]
Thank you for reporting!
As the README mentions currently pre-built binaries are provided only `arm64` and `x64` architectures (`armhf` is the 32-bit `armv7` + hardware floating point). I might try to provide `armhf` build but even in the best case it will take a while (I don't have the relevant hardware and setting up QEMU is a pain in the proverbials...).

If you need it working ASAP I can suggest either building it yourself or using Python based [wsdd](https://github.com/christgau/wsdd).

**Comment by andrewcrook** [comment]
>  `arm64` and `x64` architectures (`armhf` is the 32-bit `armv7` + hardware floating point).

Thanks for clarifying. I thought that was the case yet the notes say Raspberry PI is supported which contradicted that.
I also saw WSD for macOS in you repos. Do you happen to know if macOS will publish WSD discoveries to the network folder?

**Comment by gershnik** [comment]
Well Raspberry Pi can be `arm64` for newer hardware (see e.g. [here](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/)). 

WSD allows Windows to "see" non Windows machines so the Mac version available here will let Windows see Mac. 

Mac itself uses different mechanisms to discover what to show in _its_ network folder. In order to make Mac see Linux hosts you will need to set up [Avahi daemon](https://avahi.org) on them. There are various guides on the web on how to configure it, e.g. [this](https://phoikoi.io/2018/05/15/samba-avahi-bonjour-mac-visible.html) which comes first in my google search.

Hope it helps!

**Comment by gershnik** [comment]
`armhf` binaries are now supported. If you are still interested lease follow instructions in README on how to set up apt repo.
