### ISSUE TITLE
Error: Package systemd is not installed

### ISSUE THREAD

**Issue by kroese** [gershnik/wsdd-native#6]
I am trying to add wsddn to my Dockerfile based on Debian Trixie.

I get the following error:

```
11.45 Unpacking wsddn (1.8) ...
11.50 dpkg: dependency problems prevent configuration of wsddn:
11.50  wsddn depends on systemd; however:
11.50   Package systemd is not installed.
11.50
11.50 dpkg: error processing package wsddn (--install):
11.50  dependency problems - leaving unconfigured
11.50 Errors were encountered while processing:
11.50  wsddn
```

This is to be expected, because Debian containers have no systemd. 

Is there another way to get just the static binary installed without the whole package?

**Comment by gershnik** [comment]
Good question. I can see multiple ways of solving this but I am not a heavy Docker user and have no idea what would be the "standard" way of dealing with this. How are other networking daemons managed on this image? Does it use init rc scripts or you are supposed to start them manually?
If it uses init scripts I guess I could provide "-nosystemd" version of the package that relies on that. Or, if you are pre-building your own image anyway you could simply build it in Dockerfile.

**Comment by gershnik** [comment]
After some more reading (notably [this thread](https://lists.debian.org/debian-devel/2019/10/msg00143.html) but also others) it seems that the best solution for your situation would be to just have binaries installed with no init system interaction whatsoever. 
I could provide a "wsddn-noinit" package for that but doing it will take considerable time. If you need to be unblocked now the easiest thing is to build the code in the Dockerfile. If you want to go that route I can provide Dockerfile commands that will do the build.

**Comment by gershnik** [comment]
Here is a working Dockerfile:

```dockerfile
FROM debian:trixie

RUN apt-get update
RUN apt-get install -y 'g++'
RUN apt-get install -y ninja-build
RUN apt-get install -y wget
RUN apt-get install -y git

ARG CMAKE_VERSION=3.28.3
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /usr/bin/cmake \
      && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
      && rm /tmp/cmake-install.sh
      

ARG WSDDN_VERSION=1.8
RUN git clone --depth 1 --branch v${WSDDN_VERSION} https://github.com/gershnik/wsdd-native.git /tmp/wsdd-native \
    && /usr/bin/cmake/bin/cmake -S /tmp/wsdd-native -B /tmp/wsdd-native/build -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWSDDN_WITH_SYSTEMD=no \
    && /usr/bin/cmake/bin/cmake --build /tmp/wsdd-native/build  \
    && /usr/bin/cmake/bin/cmake --install /tmp/wsdd-native/build --prefix /usr --strip \
    && rm -rf /tmp/wsdd-native

CMD [ "/bin/bash" ]

```

**Comment by gershnik** [comment]
Well there are a couple of reasons for that difference. One is that most other network services predate systemd (by great many years in Samba case). More importantly, they have a lot of maintainers that can make sure it works correctly in both cases. I don't have either a Debian or Fedora based system without systemd or bandwidth to set one up and test installer packages there on an ongoing basis. And I don't like to ship untested code 🙂 
Thus the Debian package doesn't try to figure things out dynamically and, in fact, even the executable itself for this package is simply built linked with libsystemd rather than detect it at runtime and change logic based on that. Hence the dependency.
If there is enough interest and somebody can commit to at least test the package on non-systemd systems I'd be happy to make it dynamic.

**Comment by gershnik** [comment]
@kroese if this is still relevant, starting from version 1.12, Debian binary distribution no longer has systemd as a hard dependency and can be installed on non-systemd platforms including Docker. It also has compatible SysV init scripts so on Docker you can control it via `/etc/init.d/wsddn {start|stop|reload}` if desired.

Hope it helps!

**Comment by gershnik** [comment]
It's hard to avoid Python, isn't it? 🙂
Newer Linuxes have [KSMBD](https://docs.kernel.org/next/filesystems/cifs/ksmbd.html) - a kernel implementation of SMB that avoids Samba altogether and, as far as I know, uses the same config file format. Perhaps this can be used without Python. Haven't tried it myself though.

**Comment by gershnik** [comment]
Right, I forgot about Docker again.
However, it looks like Samba has `--disable-python --without-ad-dc` (see https://wiki.samba.org/index.php/Build_Samba_from_Source#Python) configure option that appears to build it without needing Python at all. So if you are willing to build Samba yourself it might be possible to avoid it.
