### ISSUE TITLE
Support ksmbd.mountd better versus expectation of samba being co-installed

### ISSUE THREAD

**Issue by WolfWings** [gershnik/wsdd-native#9]
Filing this issue in part as I've been migrating on my newest NAS refresh to a native ksmbd install where they've settled on (re)using the [samba configuration file format](/cifsd-team/ksmbd-tools/blob/master/ksmbd.conf.example) for the foreseeable future with the user-space daemon ksmbd.mountd.

Would it be possible to add support to detect between samba vs ksmbd.mountd, and if ksmbd.mountd is detected checking /etc/ksmbd/ksmbd.conf for the settings? I think this would only minorly impact the Config::findSmbConf function to support?

One caveat is the ksmbd userspace tools do not support any security mode except 'user' and do not even support that key, so that key being missing is considered normal in the ksmbd configuration file.

**Comment by gershnik** [comment]
Thank you for filing this! I actually looked into this issue some time ago when KSMBD was being introduced but couldn't find a satisfactory solution. Looking at my notes the main problems were:

- Both Samba and KSMBD can be simultaneously installed on the same machine (as they were on mine) with only one being "active". How do I know which one is actually being used? I guess could look for which systemd unit is active on systemd distros I guess but even that is not foolproof. 
- Where *is* the `ksmbd.conf`? Is it guaranteed to be in  `/etc/ksmbd/ksmbd.conf` or is it going to be distro specific? It wasn't clear at the time - perhaps it is now.

In the end I couldn't even make ksmbd work reliably back then so I abandoned the effort "until later times". I guess this is a good time to revisit it.

If you have any insights on how best to deal with the issues above - please let me know!

**Comment by gershnik** [comment]
Also do things currently work for you if you pass the location of ksmbd.conf via `--smb-conf` command line switch or in the `wsddn.conf` config file? The absence of security mode shouldn't be an issue - the config parser doesn't require its presence.

**Comment by WolfWings** [comment]
My apologies for the delay, I wanted to try to answer all your questions comprehensively and it took a bit to research everything as best as I could!

First, to answer your other question regarding smb-conf in config file/unit override, yes, that does work to specify it, somehow I hadn't spotted that setting when glancing over the configuration file, screen height made it land right at the edge when paging down. Specifying /etc/ksmbd/ksmbd.conf explicitly, no errors: (Censoring my internal details, they are correct though!)

```
May 12 14:01:15 chitterbox wsddn[5271]: Configuration:
May 12 14:01:15 chitterbox wsddn[5271]:     Hostname: ▒▒▒▒▒▒▒▒
May 12 14:01:15 chitterbox wsddn[5271]:     Workgoup: WORKGROUP
May 12 14:01:15 chitterbox wsddn[5271]:     Description: ▒▒▒▒▒▒▒▒
May 12 14:01:15 chitterbox wsddn[5271]:     Identifier: urn:uuid:▒▒▒▒▒▒▒▒
May 12 14:01:15 chitterbox wsddn[5271]:     Metadata: default
May 12 14:01:15 chitterbox wsddn[5271]: Starting processing
May 12 14:01:15 chitterbox wsddn[5271]: Starting interface monitor
May 12 14:01:15 chitterbox wsddn[5271]: Adding interface bond0(idx: 6), addr 192.168.86.241
May 12 14:01:15 chitterbox wsddn[5271]: Starting WSD server on bond0(idx: 6)
May 12 14:01:15 chitterbox wsddn[5271]: Starting UDP server on bond0(idx: 6)
May 12 14:01:15 chitterbox wsddn[5271]: Starting HTTP server on bond0(idx: 6)
```

w.r.t. configuration file standard location the ksmbd-tools package has only became stabilized and broadly available in winter 2021-2022, so package freezes being what they are it's only available in [fairly recent LTS-equivalent upstream distros](https://pkgs.org/search/?q=ksmbd-tools) and for RPM-based distros either 'rolling release' or from third-party repos mostly at the moment.

None of them modify upstream w.r.t. configuration file location that I can find, which more explicitly is @sysconfdir@/ksmbd/ksmbd.conf upstream which is /etc/ksmbd/ksmbd.conf (or in theory /usr/local/etc/ksmbd/ksmbd.conf). In practice I've found examining all of the packages listed in the search results expect things in /etc not /usr/local/etc though.

In regards to samba + ksmbd both being present, this was why I was suggesting it only as  fallback to check if querying 'whereis' for samba fails, as [samba plans to eventually use ksmbd as a back-end](https://wiki.samba.org/index.php/Roadmap#Infrastructure) to allow ksmbd to support more advanced features such as active directory, etc. So both being installed is valid, and broadly speaking samba would be expected to be in charge so continuing to test for samba first would be correct.

On Debian 12 at least I had to make no configuration changes to get ksmbd working out of the box, just adding shares and users with the ksmbd.add* commands after installing and (aside from lack of WSDD daemon by default) everything worked OOTB.

I did enable 'bind interfaces only' mode to disable it trying to start on the idrac interface Dell server tools create, and increased the server min protocol to SMB3_11 since I only have Windows 10 and above machines to be concerned with, but for a per-user share this configuration has worked for example including even being able to install Steam games on it as an additional mapped network drive:

```
[wolfwings]
        path = /mnt/raid/shares/wolfwings
        comment = WolfWings
        valid users = wolfwings
        force user = wolfwings
        browseable = yes
        writeable = yes
        read only = no
        guest ok = no
        create mode = 0660
        directory mode = 02775
```

I could likely optimize those settings (the permissions especially may not need to be so specific) but I just copied that share config over from my older samba NAS without issue which itself was from a previous NAS, etc, but it's a case of "my games work, so why tamper?"

**Comment by gershnik** [comment]
Thank you so much for the comprehensive investigation!! Looks like it should be pretty easy to add ksmbd support. I'll try to get to it in the next few days and, if goes well, probably cut out the next release with it towards the end of the next week.

BTW w.r.t. masking internal details, in contrast to recent change to `wsdd` and, I think, `wsdd2` behavior also, `wsdd-native` never uses any _real_ machine identifiers in WS-Discovery protocol. This is deliberate, to avoid sensitive information leakage. Instead, just like older versions of `wsdd` used to do it generates a UUID based on the machine hostname and uses it. You can override this, of course, via command line or config file if desired.

**Comment by gershnik** [comment]
This has now been released in 1.13
Let me know if it works for you.

Thanks!

**Comment by WolfWings** [comment]
🍾 Confirmed! 🎉

I reverted the smb-conf setting in /etc/wsddn.conf (AKA: commented it back out), and when restarting the service it found the ksmbd.conf file without issue, so yes it auto-detects properly!

**Comment by gershnik** [comment]
Thank you so much for verifying!
